project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  

website:
  open-graph: true
  title: "Mariah C. Boudreau"
  site-url: https://mariahcboudreau.github.io
  repo-url: https://github.com/mariahcboudreau/mariahcboudreau.github.io
  favicon: assets/images/uvm.ico
  twitter-card: 
    creator: "@Mariah-Boudreau"
    site: "@Mariah-Boudreau"
    card-style: "summary_large_image"

  navbar:
    style: "floating"
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: pages/publications.qmd
        text: Publications
      - href: portfolio/index.qmd
        text: Portfolio
        text: CV
      - href: pages/about.qmd
        text: About
      - href: blog/index.qmd
    search: true
    pinned: true

format:
  html:
    theme: spacelab
    toc: true
    smooth-scroll: true
    html-math-method: katex
    include-in-header:
      - includes.html
    footnotes-hover: false
    code-fold: true