---
title: "Publications"
---
Beauregard CG, Zimmerman JW, Fehr AMA, Tangherlini TR, Danforth CM, and Dodds PS. 
Archetypes and gender in fiction: A data-driven mapping of gender stereotypes in stories.
<a href="https://arxiv.org/abs/2602.17005">arXiv:2602.17005</a> 2026. *under consideration at EPJ Data Science

Prama TT, Beauregard CG, and Dodds PS. Self-Reported Archetypes and Behavioral 
Failures in Large Language Models. pre-print in preparation. 2026. 

Zimmeran JW, Beauregard CG, Prama TT, Suchdev P, Kollrack E, and Cramer K. Are LLM's Really Stochastic Parrots?
2026. (Ongoing: Accepted for presentation at 2026 
Institut des sciences cognitives (<a href="https://sites.grenadine.uqam.ca/sites/isc/en/iscuqam2026">Institute of Cognitive Sciences) Summer School - 
Knowledge, Reasoning, and Decision-Making</a> at 
UQAM (Université du Québec à Montréal)) 

Beauregard C, Suchdev P, Fehr AMA, Smith IT,
Tanzin Prama T, Zimmerman JW, Ward C, Lovato J, Danforth CM, Dodds PS.
Detecting sub-populations in online health communities: A mixed-methods 
exploration of breastfeeding messages in BabyCenter Birth Clubs. <a href="https://doi.org/10.48550/arXiv.2510.23692">
arXiv:2510.23692</a> [cs.SI] 27 Oct 2025. *under consideration at PLoS Digital Health

St. Onge J, Fehr AMA, Ward C, Beauregard CG, Arnold MV, Rosenblatt S, Cooley B, 
Danforth CM, Dodds S. A suite of allotaxonometric tools for the comparison of complex systems 
using rank-turbulence divergence. arXiv:<a href="https://arxiv.org/html/2506.21808v1">
2506.21808v1</a> [cs.CL] 26 Jun 2025.

Beauregard C, Danforth C, Dodds PS (2025). Misrepresentation of Overall and By-Gender Mortality 
Causes in Film Using Online, Crowd-Sourced Data: Quantitative Analysis. JMIR Formative Research.
9:e70853, DOI:<a href="https://pubmed.ncbi.nlm.nih.gov/40554798/">10.2196/70853</a>.

Zimmerman JW, Hudon D, Cramer K, Ruiz AJ, Beauregard C, Fehr A, Fudolig M, Demarest D,
Bird YM, Trujillo MZ, Danforth CM, Dodds PS (2025). Tokens, the oft-overlooked appetizer: 
Large language models, the distributional hypothesis, and meaning. arXiv:2412.10924 [cs.CL],
DOI:<a href="http://arxiv.org/abs/2412.10924">10.48550/arXiv.2412.10924</a>.

(Former name: Calla E. Y. Glavin)

Glavin C, Montgomery P (2017). Creative bibliotherapy for posttraumatic stress disorder (PTSD): a systematic review, 
Journal of Poetry Therapy, 30:2, 95-107, DOI:<a href="https://www.tandfonline.com/doi/abs/10.1080/08893675.2017.1266190">
10.1080/08893675.2017.1266190</a>.

Golecki HM, Yuan H, Glavin C, Potter B, Badrossamay MR, Goss JA, Phillips MD, Parker KK. 
Effect of solvent evaporation on fiber morphology in rotary jet spinning. 
Langmuir. 11;30(44):13369-74, DOI:<a href="https://pubs.acs.org/doi/10.1021/la5023104">
10.1021/la5023104</a>.


Yakubovich AR, Stöckl H, Murray J, Melendez-Torres GJ, Steinert JI, Glavin CEY, 
Humphreys DK. Risk and Protective Factors for Intimate Partner Violence Against Women: 
Systematic Review and Meta-analyses of Prospective-Longitudinal Studies. Am J Public Health. 
108(7):e1-e11. DOI:<a href="https://pubmed.ncbi.nlm.nih.gov/29771615/">10.2105/AJPH.2018.304428</a>. 
